package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private AlumnoId id;
     private byte[] paterno;
     private byte[] materno;
     private byte[] nombre;
     private byte[] curp;
     private byte[] correo;
     private boolean sexo;
     private Date nacimiento;
     private Date entrada;
     private Date salida;
     private boolean estado;

    public Alumno() {
    }

	
    public Alumno(AlumnoId id, byte[] paterno, byte[] materno, byte[] nombre, byte[] curp, byte[] correo, boolean sexo, Date nacimiento, Date entrada, boolean estado) {
        this.id = id;
        this.paterno = paterno;
        this.materno = materno;
        this.nombre = nombre;
        this.curp = curp;
        this.correo = correo;
        this.sexo = sexo;
        this.nacimiento = nacimiento;
        this.entrada = entrada;
        this.estado = estado;
    }
    public Alumno(AlumnoId id, byte[] paterno, byte[] materno, byte[] nombre, byte[] curp, byte[] correo, boolean sexo, Date nacimiento, Date entrada, Date salida, boolean estado) {
       this.id = id;
       this.paterno = paterno;
       this.materno = materno;
       this.nombre = nombre;
       this.curp = curp;
       this.correo = correo;
       this.sexo = sexo;
       this.nacimiento = nacimiento;
       this.entrada = entrada;
       this.salida = salida;
       this.estado = estado;
    }
   
    public AlumnoId getId() {
        return this.id;
    }
    
    public void setId(AlumnoId id) {
        this.id = id;
    }
    public byte[] getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(byte[] paterno) {
        this.paterno = paterno;
    }
    public byte[] getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(byte[] materno) {
        this.materno = materno;
    }
    public byte[] getNombre() {
        return this.nombre;
    }
    
    public void setNombre(byte[] nombre) {
        this.nombre = nombre;
    }
    public byte[] getCurp() {
        return this.curp;
    }
    
    public void setCurp(byte[] curp) {
        this.curp = curp;
    }
    public byte[] getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(byte[] correo) {
        this.correo = correo;
    }
    public boolean isSexo() {
        return this.sexo;
    }
    
    public void setSexo(boolean sexo) {
        this.sexo = sexo;
    }
    public Date getNacimiento() {
        return this.nacimiento;
    }
    
    public void setNacimiento(Date nacimiento) {
        this.nacimiento = nacimiento;
    }
    public Date getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Date entrada) {
        this.entrada = entrada;
    }
    public Date getSalida() {
        return this.salida;
    }
    
    public void setSalida(Date salida) {
        this.salida = salida;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


