package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private String nombre;

    public Area() {
    }

    public Area(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


