package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * Base generated by hbm2java
 */
public class Base  implements java.io.Serializable {


     private Integer idBase;
     private int maximo;
     private int minimo;

    public Base() {
    }

    public Base(int maximo, int minimo) {
       this.maximo = maximo;
       this.minimo = minimo;
    }
   
    public Integer getIdBase() {
        return this.idBase;
    }
    
    public void setIdBase(Integer idBase) {
        this.idBase = idBase;
    }
    public int getMaximo() {
        return this.maximo;
    }
    
    public void setMaximo(int maximo) {
        this.maximo = maximo;
    }
    public int getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(int minimo) {
        this.minimo = minimo;
    }




}


