package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CAula generated by hbm2java
 */
public class CAula  implements java.io.Serializable {


     private Integer idAula;
     private String nombre;
     private int idCTipAu;

    public CAula() {
    }

    public CAula(String nombre, int idCTipAu) {
       this.nombre = nombre;
       this.idCTipAu = idCTipAu;
    }
   
    public Integer getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(Integer idAula) {
        this.idAula = idAula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdCTipAu() {
        return this.idCTipAu;
    }
    
    public void setIdCTipAu(int idCTipAu) {
        this.idCTipAu = idCTipAu;
    }




}


