package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CCarrera generated by hbm2java
 */
public class CCarrera  implements java.io.Serializable {


     private Integer idcCarrera;
     private String nombre;

    public CCarrera() {
    }

    public CCarrera(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdcCarrera() {
        return this.idcCarrera;
    }
    
    public void setIdcCarrera(Integer idcCarrera) {
        this.idcCarrera = idcCarrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


