package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CEdificio generated by hbm2java
 */
public class CEdificio  implements java.io.Serializable {


     private Integer idCEdificio;
     private String nombre;

    public CEdificio() {
    }

    public CEdificio(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCEdificio() {
        return this.idCEdificio;
    }
    
    public void setIdCEdificio(Integer idCEdificio) {
        this.idCEdificio = idCEdificio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


