package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CLocal generated by hbm2java
 */
public class CLocal  implements java.io.Serializable {


     private Integer idCLocal;
     private int nombre;

    public CLocal() {
    }

    public CLocal(int nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCLocal() {
        return this.idCLocal;
    }
    
    public void setIdCLocal(Integer idCLocal) {
        this.idCLocal = idCLocal;
    }
    public int getNombre() {
        return this.nombre;
    }
    
    public void setNombre(int nombre) {
        this.nombre = nombre;
    }




}


