package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CTipUs generated by hbm2java
 */
public class CTipUs  implements java.io.Serializable {


     private Integer idCTipUs;
     private String nombre;

    public CTipUs() {
    }

    public CTipUs(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCTipUs() {
        return this.idCTipUs;
    }
    
    public void setIdCTipUs(Integer idCTipUs) {
        this.idCTipUs = idCTipUs;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


