package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CTipNivel generated by hbm2java
 */
public class CTipNivel  implements java.io.Serializable {


     private Integer idCTipNivel;
     private String nombre;

    public CTipNivel() {
    }

    public CTipNivel(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCTipNivel() {
        return this.idCTipNivel;
    }
    
    public void setIdCTipNivel(Integer idCTipNivel) {
        this.idCTipNivel = idCTipNivel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


