package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * CTipAu generated by hbm2java
 */
public class CTipAu  implements java.io.Serializable {


     private Integer idCTipAu;
     private String nombre;

    public CTipAu() {
    }

    public CTipAu(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdCTipAu() {
        return this.idCTipAu;
    }
    
    public void setIdCTipAu(Integer idCTipAu) {
        this.idCTipAu = idCTipAu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


