package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DEdNivAu generated by hbm2java
 */
public class DEdNivAu  implements java.io.Serializable {


     private Integer idDEdAuNiv;
     private int idCEdificio;
     private int idCTipNivel;
     private int idAula;
     private int idCLocal;

    public DEdNivAu() {
    }

    public DEdNivAu(int idCEdificio, int idCTipNivel, int idAula, int idCLocal) {
       this.idCEdificio = idCEdificio;
       this.idCTipNivel = idCTipNivel;
       this.idAula = idAula;
       this.idCLocal = idCLocal;
    }
   
    public Integer getIdDEdAuNiv() {
        return this.idDEdAuNiv;
    }
    
    public void setIdDEdAuNiv(Integer idDEdAuNiv) {
        this.idDEdAuNiv = idDEdAuNiv;
    }
    public int getIdCEdificio() {
        return this.idCEdificio;
    }
    
    public void setIdCEdificio(int idCEdificio) {
        this.idCEdificio = idCEdificio;
    }
    public int getIdCTipNivel() {
        return this.idCTipNivel;
    }
    
    public void setIdCTipNivel(int idCTipNivel) {
        this.idCTipNivel = idCTipNivel;
    }
    public int getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(int idAula) {
        this.idAula = idAula;
    }
    public int getIdCLocal() {
        return this.idCLocal;
    }
    
    public void setIdCLocal(int idCLocal) {
        this.idCLocal = idCLocal;
    }




}


