package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DGrUaal generated by hbm2java
 */
public class DGrUaal  implements java.io.Serializable {


     private Integer idDGrUaal;
     private int idDGrUa;
     private int boleta;

    public DGrUaal() {
    }

    public DGrUaal(int idDGrUa, int boleta) {
       this.idDGrUa = idDGrUa;
       this.boleta = boleta;
    }
   
    public Integer getIdDGrUaal() {
        return this.idDGrUaal;
    }
    
    public void setIdDGrUaal(Integer idDGrUaal) {
        this.idDGrUaal = idDGrUaal;
    }
    public int getIdDGrUa() {
        return this.idDGrUa;
    }
    
    public void setIdDGrUa(int idDGrUa) {
        this.idDGrUa = idDGrUa;
    }
    public int getBoleta() {
        return this.boleta;
    }
    
    public void setBoleta(int boleta) {
        this.boleta = boleta;
    }




}


