package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DHorEdNivAu generated by hbm2java
 */
public class DHorEdNivAu  implements java.io.Serializable {


     private Integer idDHorEdNivAu;
     private int idHorario;
     private int idDEdAuNiv;

    public DHorEdNivAu() {
    }

    public DHorEdNivAu(int idHorario, int idDEdAuNiv) {
       this.idHorario = idHorario;
       this.idDEdAuNiv = idDEdAuNiv;
    }
   
    public Integer getIdDHorEdNivAu() {
        return this.idDHorEdNivAu;
    }
    
    public void setIdDHorEdNivAu(Integer idDHorEdNivAu) {
        this.idDHorEdNivAu = idDHorEdNivAu;
    }
    public int getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }
    public int getIdDEdAuNiv() {
        return this.idDEdAuNiv;
    }
    
    public void setIdDEdAuNiv(int idDEdAuNiv) {
        this.idDEdAuNiv = idDEdAuNiv;
    }




}


