package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * Dia generated by hbm2java
 */
public class Dia  implements java.io.Serializable {


     private Integer idDia;
     private String nombre;

    public Dia() {
    }

    public Dia(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(Integer idDia) {
        this.idDia = idDia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


