package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DLaboArea generated by hbm2java
 */
public class DLaboArea  implements java.io.Serializable {


     private Integer idDLaboArea;
     private int idLaboratorio;
     private int idArea;

    public DLaboArea() {
    }

    public DLaboArea(int idLaboratorio, int idArea) {
       this.idLaboratorio = idLaboratorio;
       this.idArea = idArea;
    }
   
    public Integer getIdDLaboArea() {
        return this.idDLaboArea;
    }
    
    public void setIdDLaboArea(Integer idDLaboArea) {
        this.idDLaboArea = idDLaboArea;
    }
    public int getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(int idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }




}


