package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DProDis generated by hbm2java
 */
public class DProDis  implements java.io.Serializable {


     private Integer idDProDis;
     private int idDisponible;
     private int idDia;
     private int idEmpleado;

    public DProDis() {
    }

    public DProDis(int idDisponible, int idDia, int idEmpleado) {
       this.idDisponible = idDisponible;
       this.idDia = idDia;
       this.idEmpleado = idEmpleado;
    }
   
    public Integer getIdDProDis() {
        return this.idDProDis;
    }
    
    public void setIdDProDis(Integer idDProDis) {
        this.idDProDis = idDProDis;
    }
    public int getIdDisponible() {
        return this.idDisponible;
    }
    
    public void setIdDisponible(int idDisponible) {
        this.idDisponible = idDisponible;
    }
    public int getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(int idDia) {
        this.idDia = idDia;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }




}


