package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DUsAl generated by hbm2java
 */
public class DUsAl  implements java.io.Serializable {


     private Integer idDUsAl;
     private int boleta;
     private int idUsuario;

    public DUsAl() {
    }

    public DUsAl(int boleta, int idUsuario) {
       this.boleta = boleta;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdDUsAl() {
        return this.idDUsAl;
    }
    
    public void setIdDUsAl(Integer idDUsAl) {
        this.idDUsAl = idDUsAl;
    }
    public int getBoleta() {
        return this.boleta;
    }
    
    public void setBoleta(int boleta) {
        this.boleta = boleta;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


