package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * DUsEm generated by hbm2java
 */
public class DUsEm  implements java.io.Serializable {


     private Integer idDUsEm;
     private int idEmpleado;
     private int idUsuario;

    public DUsEm() {
    }

    public DUsEm(int idEmpleado, int idUsuario) {
       this.idEmpleado = idEmpleado;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdDUsEm() {
        return this.idDUsEm;
    }
    
    public void setIdDUsEm(Integer idDUsEm) {
        this.idDUsEm = idDUsEm;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


