package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * EmpleadoId generated by hbm2java
 */
public class EmpleadoId  implements java.io.Serializable {


     private int idEmpleado;
     private int idBase;
     private int idInterinato;

    public EmpleadoId() {
    }

    public EmpleadoId(int idEmpleado, int idBase, int idInterinato) {
       this.idEmpleado = idEmpleado;
       this.idBase = idBase;
       this.idInterinato = idInterinato;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdBase() {
        return this.idBase;
    }
    
    public void setIdBase(int idBase) {
        this.idBase = idBase;
    }
    public int getIdInterinato() {
        return this.idInterinato;
    }
    
    public void setIdInterinato(int idInterinato) {
        this.idInterinato = idInterinato;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoId) ) return false;
		 EmpleadoId castOther = ( EmpleadoId ) other; 
         
		 return (this.getIdEmpleado()==castOther.getIdEmpleado())
 && (this.getIdBase()==castOther.getIdBase())
 && (this.getIdInterinato()==castOther.getIdInterinato());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpleado();
         result = 37 * result + this.getIdBase();
         result = 37 * result + this.getIdInterinato();
         return result;
   }   


}


