package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private int idLaboratorio;

    public Laboratorio() {
    }

    public Laboratorio(int idLaboratorio) {
       this.idLaboratorio = idLaboratorio;
    }
   
    public int getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(int idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }




}


