package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Semestre generated by hbm2java
 */
public class Semestre  implements java.io.Serializable {


     private Integer idSemestre;
     private String tipo;
     private int ano;
     private Date inicio;
     private Date fin;

    public Semestre() {
    }

    public Semestre(String tipo, int ano, Date inicio, Date fin) {
       this.tipo = tipo;
       this.ano = ano;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public Integer getIdSemestre() {
        return this.idSemestre;
    }
    
    public void setIdSemestre(Integer idSemestre) {
        this.idSemestre = idSemestre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


