package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * UniAprendHasPlanEstudiosId generated by hbm2java
 */
public class UniAprendHasPlanEstudiosId  implements java.io.Serializable {


     private int idUniAprend;
     private int idplanEstudios;

    public UniAprendHasPlanEstudiosId() {
    }

    public UniAprendHasPlanEstudiosId(int idUniAprend, int idplanEstudios) {
       this.idUniAprend = idUniAprend;
       this.idplanEstudios = idplanEstudios;
    }
   
    public int getIdUniAprend() {
        return this.idUniAprend;
    }
    
    public void setIdUniAprend(int idUniAprend) {
        this.idUniAprend = idUniAprend;
    }
    public int getIdplanEstudios() {
        return this.idplanEstudios;
    }
    
    public void setIdplanEstudios(int idplanEstudios) {
        this.idplanEstudios = idplanEstudios;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UniAprendHasPlanEstudiosId) ) return false;
		 UniAprendHasPlanEstudiosId castOther = ( UniAprendHasPlanEstudiosId ) other; 
         
		 return (this.getIdUniAprend()==castOther.getIdUniAprend())
 && (this.getIdplanEstudios()==castOther.getIdplanEstudios());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUniAprend();
         result = 37 * result + this.getIdplanEstudios();
         return result;
   }   


}


