package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * UniAprendHasPlanEstudios generated by hbm2java
 */
public class UniAprendHasPlanEstudios  implements java.io.Serializable {


     private UniAprendHasPlanEstudiosId id;

    public UniAprendHasPlanEstudios() {
    }

    public UniAprendHasPlanEstudios(UniAprendHasPlanEstudiosId id) {
       this.id = id;
    }
   
    public UniAprendHasPlanEstudiosId getId() {
        return this.id;
    }
    
    public void setId(UniAprendHasPlanEstudiosId id) {
        this.id = id;
    }




}


