package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * UniAprend generated by hbm2java
 */
public class UniAprend  implements java.io.Serializable {


     private int idUniAprend;
     private String nombre;
     private float creditos;
     private float horas;

    public UniAprend() {
    }

    public UniAprend(int idUniAprend, String nombre, float creditos, float horas) {
       this.idUniAprend = idUniAprend;
       this.nombre = nombre;
       this.creditos = creditos;
       this.horas = horas;
    }
   
    public int getIdUniAprend() {
        return this.idUniAprend;
    }
    
    public void setIdUniAprend(int idUniAprend) {
        this.idUniAprend = idUniAprend;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(float creditos) {
        this.creditos = creditos;
    }
    public float getHoras() {
        return this.horas;
    }
    
    public void setHoras(float horas) {
        this.horas = horas;
    }




}


