package model;
// Generated 11-jul-2015 1:33:51 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

     private Integer idUsuario;
     private byte[] pass;
     private int idCTipUs;
     private int idFoto;
     public Usuario(Usuario newest) {
       this.pass = newest.pass;
       this.idCTipUs = newest.idCTipUs;
       this.idFoto = newest.idFoto;
    }
     public void copy(Usuario newest){
        if(newest.pass != null)this.pass = newest.pass;
        if(newest.idCTipUs != 0)this.idCTipUs = newest.idCTipUs;
        if(newest.idFoto !=0)this.idFoto = newest.idFoto;
     }
    public Usuario() {
    }

    public Usuario(byte[] pass, int idCTipUs, int idFoto) {
       this.pass = pass;
       this.idCTipUs = idCTipUs;
       this.idFoto = idFoto;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public byte[] getPass() {
        return this.pass;
    }
    
    public void setPass(byte[] pass) {
        this.pass = pass;
    }
    public int getIdCTipUs() {
        return this.idCTipUs;
    }
    
    public void setIdCTipUs(int idCTipUs) {
        this.idCTipUs = idCTipUs;
    }
    public int getIdFoto() {
        return this.idFoto;
    }
    
    public void setIdFoto(int idFoto) {
        this.idFoto = idFoto;
    }


}


